// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttjhbyvbmckgwvluadkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0amhieXZibWNrZ3d2bHVhZGt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1OTAyMzQsImV4cCI6MjA2NTE2NjIzNH0.U3lxu_kA5JHDtKEVu7KE3qXykoZRj9dVWzSrLljTv-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});